// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umylzsfmovdxdtahsvqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVteWx6c2Ztb3ZkeGR0YWhzdnFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NjQ1NDAsImV4cCI6MjA2NDM0MDU0MH0.ZeFiTb_5Xm_jR1Ua6M_2tmk-ckyaf8sGrCCV9nfnJM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);